// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAarGIvmQ8omu5Eq0Yb-6IsJkSF8wTNKGM',
//     appId: '1:658427837597:web:e5cb97e5098cb572ffe874',
//     messagingSenderId: '658427837597',
//     projectId: 'letsfind-44240',
//     authDomain: 'letsfind-44240.firebaseapp.com',
//     storageBucket: 'letsfind-44240.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBtiOraUV5cxkG5P-BZ1JDUoyos8ZP4hxg',
//     appId: '1:658427837597:android:f37df9bb4a323d7fffe874',
//     messagingSenderId: '658427837597',
//     projectId: 'letsfind-44240',
//     storageBucket: 'letsfind-44240.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCnIS82rfHxSmpL-w8fSonM5Ht6-_lM0Uo',
//     appId: '1:658427837597:ios:73b8e838737f9ed3ffe874',
//     messagingSenderId: '658427837597',
//     projectId: 'letsfind-44240',
//     storageBucket: 'letsfind-44240.appspot.com',
//     iosBundleId: 'com.app.letsfind',
//   );
// }
